# This pipeline publishes the `@kth/canvas-api` package to npm
pr: none
trigger:
  branches:
    include:
      - main
      - v5

variables:
  - group: team-elarande-general-params

steps:
  - checkout: self
    path: github

  - task: NodeTool@0
    inputs:
      versionSource: "spec"
      versionSpec: 20.x

  - task: Npm@1
    displayName: Run `npm ci`
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: ci

  - task: Npm@1
    displayName: Run `npm run build`
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: custom
      customCommand: run build

  - task: Npm@1
    displayName: Run `npm test`
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: custom
      customCommand: test

  - task: Npm@1
    displayName: Publish to npm
    inputs:
      workingDir: "$(Pipeline.Workspace)/github"
      command: publish
      publishRegistry: useExternalRegistry
      publishEndpoint: $(npmServiceConnection)
